resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: 010741811189.dkr.ecr.us-east-1.amazonaws.com/backend
<<<<<<< HEAD
    newTag: 5ed3d14ca0e5ab8ae5a34c37e71f8db5e2febd9b
=======
    newTag: 5ed3d14ca0e5ab8ae5a34c37e71f8db5e2febd9b
>>>>>>> 6a09d7a (deployment files fixx)
