apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: 010741811189.dkr.ecr.us-east-1.amazonaws.com/frontend:dfa89be89b957872fa7552b4dc6a1d2fe6be6eda

          ports:
            - containerPort: 80
