apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: 010741811189.dkr.ecr.us-east-1.amazonaws.com/frontend:912885053a6bfe9d90815da9e4817559c42e3b93

          ports:
            - containerPort: 80
