apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: 010741811189.dkr.ecr.us-east-1.amazonaws.com/frontend:bd4a9fa19e8238a7960a3371b2ce178ac210c3ba

          ports:
            - containerPort: 80
