- name: Promote Backend to Staging
  env:
    GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
  run: |
    git clone https://github.com/Uprightbalance/gitops-repo.git
    cd gitops-repo

    git remote set-url origin https://$GITOPS_TOKEN@github.com/Uprightbalance/gitops-repo.git

    DEV_TAG=$(grep newTag k8s/backend/dev/kustomization.yaml | awk '{print $2}')

    sed -i "s/newTag:.*/newTag: $DEV_TAG/" k8s/backend/staging/kustomization.yaml

    git config user.email "uprightojieh316@gmail.com"
    git config user.name "github-actions"

    git commit -am "promote backend $DEV_TAG to staging"

    git push origin main
